### ISSUE TITLE
Move repo to wolberlab organization

### ISSUE THREAD

**Issue by dominiquesydow** [wolberlab/dynophores#45]
## Description
Move repo to @wolberlab: https://github.com/wolberlab

## Todos
- [x] Transfer repo; [GH documentation](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository)
- [x] Update all https://github.com/dominiquesydow/dynophores references (note: old URL will redirect to new URL; we will do the update anyways to avoid future dominiquesydow/wolberlab mixtures in the docs ect.)
  - [x] https://github.com/wolberlab/dynophores
    - `README.md`
    - `docs/installing.rst`
    - `dynophores/visz/view3d/interactive.py`
  - [x] https://github.com/conda-forge/dynophores-feedstock
    - `README.md`
    - `meta.yaml`
  - [x] https://dynophores.readthedocs.io/
    - Update https://readthedocs.org/dashboard/dynophores/edit/
